swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

host: localhost:3000
basePath: /v1


schemes:
  - http

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK

    delete:
      summary: Deletes a user.
      produces:
        - application/json
      parameters:
        - name: id
          in: query
          description: ID of the user that needs to be deleted
          type: string
          required: true
      responses:
        200:
          description: OK

    put:
      summary: Update user.
      produces:
          - application/json
      parameters:
        - name: id
          in: query
          description: ID of the user that needs to be updated
          type: string
          required: true
        - name: nome
          in: formData
          description: Nome do usuário
          type: string
          required: true
        - name: sobrenome
          in: formData
          description: Sobrenome do usuário
          type: string
          required: true
        - name: email
          in: formData
          description: Endereço de e-mail do usuário
          type: string
          required: true
        - name: cpf
          in: formData
          description: CPF do usuário
          type: string
          required: true
      responses:
          200:
            description: OK

  /users/{id}:
    get:
      summary: Get user by ID.
      parameters:
        - name: id
          in: path
          description: ID of the user to retrieve
          required: true
          type: string
      responses:
        '200':
          description: OK

    patch:
      summary: Update user.
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of the user that needs to be updated
          type: string
          required: true
        - name: body
          in: body
          description: User object with updated fields
          required: true
          schema:
            type: object
            properties:
              nome:
                type: string
              sobrenome:
                type: string
              email:
                type: string
              cpf:
                type: string
      responses:
        '200':
          description: OK

  /add:
    post:
      summary: Add new user.
      produces:
        - application/json
      parameters:
        - name: nome
          in: formData
          description: Nome do usuário
          type: string
          required: true
        - name: sobrenome
          in: formData
          description: Sobrenome do usuário
          type: string
          required: true
        - name: email
          in: formData
          description: Endereço de e-mail do usuário
          type: string
          required: true
        - name: cpf
          in: formData
          description: CPF do usuário
          type: string
          required: true
      responses:
        200:
          description: OK

